# Install Config
api: 3
name: Test-Suite
author: Prasad T
# Configuration
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: true
    # Add Repos
    # individual repos flags are mentioned under config.add_repo key
    add_repo: true
    # Add PPAs
    ppa: true
    # APT Packages
    apt: true
    # Whether to purge packages mentioned in config.purge key
    purge: false
    debs: true
    binaries: false
    snaps: false
  # Repository Flags
  add_repo:
    bazel: false
    brave_browser: true
    chrome: true
    docker: false
    edge: false
    element_io: true
    # This is really flaky so drop it
    gcsfuse: false
    github: true
    googlecloud: false
    gvisor: false
    hashicorp: false
    mendeley: false
    miniconda: false
    neurodebian: false
    podman: false
    protonvpn: false
    ros: false
    ros2: false
    signal: true
    skype: false
    spotify: true
    slack: false
    sublimetext: true
    teams: false
    vivaldi: true
    vscode: true
    winehq: true
    # Debian
    debian_nonfree: false
    debian_contrib: false
    # Ubuntu
    ubuntu_universe: false
    ubuntu_multiverse: false
    ubuntu_restricted: false

  # Flags
  flags:
    purge_enabled: false
    preserve_debs: false

  # Packages to purge
  purge:
    - 
  # PPA
  ppa:
    # With prefix ppa:
    - ppa:yubico/stable
  # Install components
  # APT Packages, Python Modules, Debian packages
  install:
    snaps:
      - 
    # Debian packages/.deb files
    debs:
      - https://mullvad.net/download/app/deb/latest
      - https://discord.com/api/download?platform=linux&format=deb
    binaries:
      - 
    apt:
      # Admin related Stuff
      administration:
        - curl
      # Security Related Stuff
      security:
        - gnupg2
        - ufw
        - nmap
        - fail2ban
      # Productivity & Office Tools.
      productivity:
        - curl
      # Tools related to development.
      development:
        - iputils-ping
      # Everything Else
      other:
        - less
      external:
        # spotify
        - spotify-client
        # git
        - git
        # Microsoft VSCode
        - code
        # Google
        - google-chrome-stable
        # Signal
        - signal-desktop
        # Sublime
        - sublime-text
        # Non-free in debian, multiverse in Ubuntu(canonical partner repos)
        - unrar
        # Brave
        - brave-browser
        # Vivaldi
        - vivaldi-stable
        # Telegram
        - telegram-desktop
        # anki
        - anki
        # calibre
        - calibre 
        # torrent
        - qbittorrent
        # guake
        - guake
        # zsh
        - zsh
        # neofetch
        - neofetch
        # tldr
        - tldr
        # gedit
        - gedit
        # flameshot
        - flameshot
        - vlc
        - youtube-dl
        - feedreader
        - onionshare
        - htop