name: docs
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install git-chglog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

      - name: Generate changelog
        run: |
          ./scripts/changelog.sh \
            --changelog \
            --oldest-tag "v7.0.0" \
            --footer-file .chglog/OLD_CHGLOG.md \
            --output docs/changelog.md \
            --repository "https://github.com/tprasadtp/ubuntu-post-install"
          cat docs/changelog.md

      - name: Generate release notes
        run: |
          ./scripts/changelog.sh --release-notes --repository "https://github.com/tprasadtp/ubuntu-post-install" --output RELEASE_NOTES.md
          cat RELEASE_NOTES.md

      - name: Build Docs
        run: |
          ./build/docs.sh
          cat ./_site/commit.json
